apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-ya0l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-ya0l
    app.kubernetes.io/part-of: load-app-39dddbbf-b891-4b55-a798-146b85f899d3
  name: devfile-sample-java-sprinvgld
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-java-springboot-basic-ya0l
    weight: null
status: {}
